# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 0, 521, 181))
        self.label.setStyleSheet("font-size: 28pt;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 420, 200, 80))
        self.pushButton.setStyleSheet("font-size: 15pt;")
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 270, 378, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.targetDirLabel = QtWidgets.QLabel(self.layoutWidget)
        self.targetDirLabel.setStyleSheet("font-size: 10pt;")
        self.targetDirLabel.setObjectName("targetDirLabel")
        self.horizontalLayout_2.addWidget(self.targetDirLabel)
        self.targetDirText = QtWidgets.QLineEdit(self.layoutWidget)
        self.targetDirText.setObjectName("targetDirText")
        self.horizontalLayout_2.addWidget(self.targetDirText)
        self.browseTargetDir = QtWidgets.QPushButton(self.layoutWidget)
        self.browseTargetDir.setObjectName("browseTargetDir")
        self.horizontalLayout_2.addWidget(self.browseTargetDir)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 210, 378, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.referenceLabel = QtWidgets.QLabel(self.widget)
        self.referenceLabel.setStyleSheet("font-size: 10pt;")
        self.referenceLabel.setObjectName("referenceLabel")
        self.horizontalLayout.addWidget(self.referenceLabel)
        self.referenceText = QtWidgets.QLineEdit(self.widget)
        self.referenceText.setObjectName("referenceText")
        self.horizontalLayout.addWidget(self.referenceText)
        self.browseReference = QtWidgets.QPushButton(self.widget)
        self.browseReference.setObjectName("browseReference")
        self.horizontalLayout.addWidget(self.browseReference)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "AWS Rekognition Image Sorter"))
        self.pushButton.setText(_translate("MainWindow", "Begin Processing!"))
        self.targetDirLabel.setText(_translate("MainWindow", "Target Directory  "))
        self.browseTargetDir.setText(_translate("MainWindow", "Browse"))
        self.referenceLabel.setText(_translate("MainWindow", "Reference Picture"))
        self.browseReference.setText(_translate("MainWindow", "Browse"))
        self.browseReference.clicked.connect(self.browseReference_handler)
        self.browseTargetDir.clicked.connect(self.browseTargetDir_handler)

    def browseReference_handler(self):
        print("Browse reference handler clicked")
        filename = QtWidgets.QFileDialog.getOpenFileName()
        print(filename[0])

    def browseTargetDir_handler(self):
        print("Browse TargetDir handler clicked")
        targetDir = QtWidgets.QFileDialog.getExistingDirectory(None, 'Select project folder:', 'F:\\', QtWidgets.QFileDialog.ShowDirsOnly)
        print(targetDir)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
